version: "3.7"
services:
  jamulus:
    container_name: jamulus 
    image: taghor/jamulus:latest
    restart: unless-stopped
    ports:
      - "22124:22124/udp"
    environment:
      TZ: "Germany/Berlin"  
    entrypoint:
      - "Jamulus"
      - "--server"
      - "--nogui"
      - "--multithreading"
      - "--welcomemessage"
      - "${WELCOME_MESSAGE}"
      - "--numchannels"
      - "16"
    healthcheck:
      test: ["CMD-SHELL", "nc -zu localhost 22124 || exit 1"]
      interval: 60s
      retries: 5
      start_period: 20s
      timeout: 10s
