version: "3.7"

services:
  jamulus:
    container_name: jamulus 
    image: taghor/jamulus:latest
    restart: unless-stopped
    networks:
      - web
    environment:
      TZ: "Germany/Berlin"  
    entrypoint:
      - "Jamulus"
      - "--server"
      - "--nogui"
      - "--multithreading"
      - "--welcomemessage"
      - "${WELCOME_MESSAGE}"
      - "--numchannels"
      - "16"
    healthcheck:
      test: ["CMD-SHELL", "nc -zu localhost 22124 || exit 1"]
      interval: 60s
      retries: 5
      start_period: 20s
      timeout: 10s
    labels:
      traefik.enable: true

      traefik.udp.routers.jamulus.entrypoints: jamulus
      traefik.udp.routers.jamulus.service: jamulus
      traefik.udp.services.jamulus.loadbalancer.server.port: 22124

      traefik.docker.network: web

networks:
    web:
       external: true

